In [6]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

In [5]:
dt = pd.read_csv('mushrooms.csv')
print(dt.shape)
dt.head(10)

(8124, 23)


class cap-shape cap-surface cap-color bruises odor gill-attachment  \
0     p         x           s         n       t    p               f   
1     e         x           s         y       t    a               f   
2     e         b           s         w       t    l               f   
3     p         x           y         w       t    p               f   
4     e         x           s         g       f    n               f   
5     e         x           y         y       t    a               f   
6     e         b           s         w       t    a               f   
7     e         b           y         w       t    l               f   
8     p         x           y         w       t    p               f   
9     e         b           s         y       t    a               f   

  gill-spacing gill-size gill-color   ...   stalk-surface-below-ring  \
0            c         n          k   ...                          s   
1            c         b          k   ...                          s   
2            c         b          n   ...                          s   
3            c         n          n   ...                          s   
4            w         b          k   ...                          s   
5            c         b          n   ...                          s   
6            c         b          g   ...                          s   
7            c         b          n   ...                          s   
8            c         n          p   ...                          s   
9            c         b          g   ...                          s   

  stalk-color-above-ring stalk-color-below-ring veil-type veil-color  \
0                      w                      w         p          w   
1                      w                      w         p          w   
2                      w                      w         p          w   
3                      w                      w         p          w   
4                      w                      w         p          w   
5                      w                      w         p          w   
6                      w                      w         p          w   
7                      w                      w         p          w   
8                      w                      w         p          w   
9                      w                      w         p          w   

  ring-number ring-type spore-print-color population habitat  
0           o         p                 k          s       u  
1           o         p                 n          n       g  
2           o         p                 n          n       m  
3           o         p                 k          s       u  
4           o         e                 n          a       g  
5           o         p                 k          n       g  
6           o         p                 k          n       m  
7           o         p                 n          s       m  
8           o         p                 k          v       g  
9           o         p                 k          s       m  

[10 rows x 23 columns]

## Encoding into numerical data



In [10]:
le = LabelEncoder()
# le.fit_transform?

ds = dt.apply(le.fit_transform)
ds.head()

class  cap-shape  cap-surface  cap-color  bruises  odor  gill-attachment  \
0      1          5            2          4        1     6                1   
1      0          5            2          9        1     0                1   
2      0          0            2          8        1     3                1   
3      1          5            3          8        1     6                1   
4      0          5            2          3        0     5                1   

   gill-spacing  gill-size  gill-color   ...     stalk-surface-below-ring  \
0             0          1           4   ...                            2   
1             0          0           4   ...                            2   
2             0          0           5   ...                            2   
3             0          1           5   ...                            2   
4             1          0           4   ...                            2   

   stalk-color-above-ring  stalk-color-below-ring  veil-type  veil-color  \
0                       7                       7          0           2   
1                       7                       7          0           2   
2                       7                       7          0           2   
3                       7                       7          0           2   
4                       7                       7          0           2   

   ring-number  ring-type  spore-print-color  population  habitat  
0            1          4                  2           3        5  
1            1          4                  3           2        1  
2            1          4                  3           2        3  
3            1          4                  2           3        5  
4            1          0                  3           0        1  

[5 rows x 23 columns]

In [34]:
data  = ds.values

print(data[:5,:])

Y = data[:,0]
X = data[:,1:]
print(X.shape)
print(Y.shape)

[[1 5 2 4 1 6 1 0 1 4 0 3 2 2 7 7 0 2 1 4 2 3 5]
 [0 5 2 9 1 0 1 0 0 4 0 2 2 2 7 7 0 2 1 4 3 2 1]
 [0 0 2 8 1 3 1 0 0 5 0 2 2 2 7 7 0 2 1 4 3 2 3]
 [1 5 3 8 1 6 1 0 1 5 0 3 2 2 7 7 0 2 1 4 2 3 5]
 [0 5 2 3 0 5 1 1 0 4 1 3 2 2 7 7 0 2 1 0 3 0 1]]
(8124, 22)
(8124,)


In [35]:
x_train,x_test,y_train,y_test = train_test_split(X,Y,test_size = 0.2)

In [36]:
print(x_train.shape)
print(y_train.shape)

(6499, 22)
(6499,)


## Classifier

In [66]:
def prior_prob(y_train,label):
    
    tot = y_train.shape[0]
    num = np.sum(y_train==label)
    
    return num/float(tot)




In [67]:
def conditional_prob(x_train,y_train,feat_col,feat_val,label):
    
    
    x_filterd = x_train[y_train==label]
    
    numerator = np.sum(x_filterd[:,feat_col]==feat_val)
    
    denom = np.sum(y_train==label)
    
    return numerator/float(denom)


## Posterior Probability

In [68]:
def predict(x_train,y_train,xtest):
    
    posts=[]
    n_features = x_train.shape[1]
    
    for ix in np.unique(y_train):
        likelihood=1.0
        for iy in range(n_features): 
            likelihood *= conditional_prob(x_train,y_train,iy,xtest[iy],ix) 
       
        prior =  prior_prob(y_train,ix)
        post = likelihood*prior
        posts.append(post)
    
    return np.argmax(posts)
                

## Testing

In [79]:
def score(x_train,y_train,x_test,y_test):
    
    
    predictions = []
    for ix in range(x_test.shape[0]):
        
        pred = predict(x_train,y_train,x_test[ix])
        predictions.append(pred)
    
    
    predictions=np.array(predictions)
   
    ans = (np.sum(predictions==y_test))/float(x_test.shape[0])
    
    return ans


In [80]:
# x_train.shape
print(score(x_train,y_train,x_test,y_test))
# print(y_test.shape)

0.9969230769230769


## 99.69 % Accuracy on testing Set